name: "Build + Coverage"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Run once per day to detect broken dependencies.
    - cron: '33 5 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        ros_distribution: [ foxy, galactic, rolling ]
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: ros-tooling/setup-ros@v0.2
      with:
        required-ros-distributions: ${{ matrix.ros_distribution }}
    - uses : ros-tooling/action-ros-ci@v0.2
      with:
        package-name: "micro_ros_diagostic_updater micro_ros_diagostic_msgs micro_ros_diagostic_bridge micro_ros_commons_diagostics"
        target-ros2-distro: ${{ matrix.ros_distribution }}
        colcon-defaults: |
          {
            "build": {
              "mixin": ["coverage-gcc", "coverage-pytest"]
            },
            "test": {
              "mixin": ["coverage-pytest"]
            }
          }
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
    - uses: codecov/codecov-action@v1.5.0
      with:
        file: ros_ws/lcov/total_coverage.info
