name: "Build action: Foxy + Rolling"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Run once per day to detect broken dependencies.
    - cron: '33 5 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        ros_distribution: [ foxy, rolling ]
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@0.1.2
      with:
        required-ros-distributions: ${{ matrix.ros_distribution }}
    - uses : ros-tooling/action-ros-ci@0.1.1
      with:
        package-name: "micro_ros_diagnostic_msgs micro_ros_diagnostic_updater micro_ros_common_diagnostics"
        vcs-repo-file-url: ""
        target-ros2-distro: ${{ matrix.ros_distribution }}
        colcon-mixin-name: coverage-gcc
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
    - uses: codecov/codecov-action@v1.2.2
      with:
        file: ros_ws/lcov/total_coverage.info
